name: esmaulhusna_muslimbg
description: Flutter package for Esmaul Husna / Asma ul Husna with Arabic text, meanings, offline JSON data, and Balkan locale support for Islamic apps.
version: 1.0.7
repository: https://github.com/cemalkarabulakli/esmaulhusna_muslimbg
homepage: https://github.com/cemalkarabulakli/esmaulhusna_muslimbg
issue_tracker: https://github.com/cemalkarabulakli/esmaulhusna_muslimbg/issues
documentation: https://github.com/cemalkarabulakli/esmaulhusna_muslimbg/wiki

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/translations/

topics:
  - islam
  - quran
  - flutter
  - localization
  - dua
