# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      # Specify the github actions deployment environment
      environment: cemal_esmaulhusna
      working-directory: esmaulhusna_muslimbg