# A CI configuration to auto-publish pub packages.

name: Publish

on: 
  push:
    branches:
      - main

jobs:
  publish:
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    permissions: 
      id-token: write
    with:
      environment: cemal_esmaulhusna
      write-comments: false