# A CI configuration to write comments on PRs.

name: Comment on the pull request

on:
  workflow_run:
    workflows: 
      - Publish
    types:
      - completed

jobs:
    publish:
      uses: dart-lang/ecosystem/.github/workflows/publish.yml@main
      with:
        environment: pub.dev # Can be any name, this is the convention though.      