name: Publish to pub.dev

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest' # Specify the Flutter version you want to use

      - name: Install dependencies
        working-directory: ./esmaulhusna # Set the working directory to your project root
        run: flutter pub get # Use flutter pub instead of dart pub

      - name: Publish package
        working-directory: ./esmaulhusna # Set the working directory to your project root
        run: flutter pub publish --force