name: Publish to pub.dev

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Use stable channel instead of specific version

      - name: Install dependencies
        run: flutter pub get # Use flutter pub instead of dart pub

      - name: Publish package
        run: flutter pub publish --force